### ISSUE TITLE
Tmux + Tests: Is there a way to automate it exit from visual/search mode?

### ISSUE THREAD

**Issue by tscolari** [luan/nvim#101]
Hey there!

I've done some research but couldn't find anything in the subject, I don't know if more people use vim inside tmux, I really like the testing shortcuts and I use it all the time.
But one thing has driven me crazy for months and since I couldn't figure out how to fix it by myself I'm asking for help 😓 

The scenario is, you hit the short cut, and the tests run in the tmux panel for you, it works as intended. Then you scroll up that panel (entering visual/search mode) find what went wrong with the test, go back to vim and run the test short cut again.
That sends the test string to the visual mode of tmux instead of inserting it in the panel, which depending on the day can drive you crazy!

Is there a way for the shortcut to also "exit" the search mode?
Am I the only one that have this issue? 😢 

Many thanks in advance for any help!

**Comment by albertoleal** [comment]
@tscolari we use `vimux` [here](https://github.com/luan/nvim/blob/681f236867540d0c4544df15fa59f6fd8bf93687/lua/plugins/test.lua#L2) and you can add another configuration to do what you want:

```
vim.g['test#preserve_screen'] = 0
```

From: https://github.com/vim-test/vim-test

**Comment by tscolari** [comment]
That works!
