### ISSUE TITLE
Consider using coc.nvim

### ISSUE THREAD

**Issue by lorenzo** [luan/nvim#13]
Hi!

I've been using your distribution for a few month already and I'm really thankful of the good work you've done putting this together. Yesterday I gave [coc.nvim](https://github.com/neoclide/coc.nvim) a try and I have to say it is leaps and bounds better than any other LanguageClient I've tried before. 

I had to modify quite a few files to get this to work correctly, and I'd like to bring it to your consideration in the hope that I don't have to fork this project. These were my changes:

* Removed deoplete
* Added `coc#status` to the lightline
* Removed plugin `tpope/vim-endwise` as it was interfering with a smoother autocomplete experience. This plugin can probably be kept by replicating the same tricks you did for closing the deplete window when hitting enter
* Removed plugin `Shougo/echodoc`. Coc offers a much better alternative out of the box.

Let me know if you'd wish I send a pull request with my suggested changes, if this is of any interest to you.

**Comment by luan** [comment]
This looks fantastic. I'll definitely take a deeper look at it very soon. Thanks for the pointer!

**Comment by luan** [comment]
Can you show me the coc-config you used? Also, which extensions did you try so far?

**Comment by lorenzo** [comment]
This is my config for coc.nvim

```vim
" if hidden is not set, TextEdit might fail.
set hidden

" Better display for messages
"set cmdheight=2

" Smaller updatetime for CursorHold & CursorHoldI
set updatetime=300

" don't give |ins-completion-menu| messages.
set shortmess+=c

" always show signcolumns
set signcolumn=yes

" Use tab for trigger completion with characters ahead and navigate.
" Use command ':verbose imap <tab>' to make sure tab is not mapped by other plugin.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> for trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()

" Use <cr> for confirm completion, `<C-g>u` means break undo chain at current position.
" Coc only does snippet and additional edit on confirm.
inoremap <expr><cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

" Use `[c` and `]c` for navigate diagnostics
nmap <silent> [c <Plug>(coc-diagnostic-prev)
nmap <silent> ]c <Plug>(coc-diagnostic-next)

" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K for show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if &filetype == 'vim'
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Highlight symbol under cursor on CursorHold
autocmd CursorHold * silent call CocActionAsync('highlight')

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Use `:Format` for format current buffer
command! -nargs=0 Format :call CocAction('format')

" Use `:Fold` for fold current buffer
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Remap for do codeAction of selected region, ex: `<leader>aap` for current paragraph


let g:lmap.l = { 'name': 'Language Server' }
let g:lmap.l.d =  [':CocList diagnostics',              'Diagnostics']
let g:lmap.l.e =  [':CocList extensions',               'Extensions']
let g:lmap.l.c =  [':CocList commands',                 'Commands']
let g:lmap.l.o =  [':CocList outline',                  'Outline']
let g:lmap.l.s =  [':Vista finder coc',                 'Symbols']
let g:lmap.l.t =  [':Vista coc',                        'Tag Bar']
let g:lmap.l.ct = [':Vista!',                           'Close Tag Bar']
let g:lmap.l.j =  [':CocNext',                          'Next Action']
let g:lmap.l.k =  [':CocPrev',                          'Prev Action']
let g:lmap.l.p =  [':CocListResume',                    'Resume latest list']
let g:lmap.l.k =  [':call CocAction("doHover")',        'Hover']

let g:lmap.l.a =  ['call feedkeys("\<Plug>(coc-codeaction)")',              'Code Action']
let g:lmap.l.as = ['call feedkeys("\<Plug>(coc-codeaction-selected)")',     'Code Action Selected']
let g:lmap.l.r =  ['call feedkeys("\<Plug>(coc-rename)")',                  'Rename']
let g:lmap.l.f =  ['call feedkeys("\<Plug>(coc-format)")',                  'Format']
let g:lmap.l.fs = ['call feedkeys("\<Plug>(coc-format-selected)")',         'Format Selected']
let g:lmap.l.qf = ['call feedkeys("\<Plug>(coc-fix-current)")',             'Quick Fix']
```

I enabled the following extensions, and liked how they work so far:

* coc-json
* coc-tsserver
* coc-html
* coc-css
* coc-yaml
* coc-python
* coc-emmet

**Comment by luan** [comment]
Alright, thanks so much for that.
I just pushed a commit that will use coc.nvim *if* `yarn` is available on the `PATH`. I know a lot of people that use this config don't even have nodejs installed so I want to ease into that for a bit. I'll use the config with this enabled during next week and depending on how it goes I might properly deprecate the old stuff and start telling people that node/yarn are needed.

Thank you so much for the suggestion. So far I'm loving coc.nvim. Especially after installing neovim from master and seeing all the super duper cool stuff with floating windows they're doing. I think there are still some rough edges but it still feels like an improvement.

I'm leaving this issue open for now until I make a final decision on when to stop using deoplete.

**Comment by lorenzo** [comment]
Great! Thanks for looking into this
