### ISSUE TITLE
Local changes break auto-update

### ISSUE THREAD

**Issue by tjvman** [luan/nvim#14]
We had staged local modifications to our clone of this repo, which caused nvim to try and update every time we opened a new neovim session. While we were able to resolve the problem by discarding the staged changes, it was difficult to diagnose why the repeated updates were occurring.

It would be nice to have a clearer message that there are discrepancies between the local state and the remote.

**Comment by luan** [comment]
Were you not seeing this: https://github.com/luan/nvim/blob/master/update.vim#L83-L85 ?

**Comment by tjvman** [comment]
We were not.
