### ISSUE TITLE
go.mod automatically updated

### ISSUE THREAD

**Issue by tylerphelan** [luan/nvim#15]
We're noticing that our `go.mod` file gets updated if we open a session inside a go mod project. The packages added are:
```
+ golang.org/x/crypto v0.0.0-20190506204251-e1dfcc566284 // indirect
+ golang.org/x/net v0.0.0-20190503192946-f4e77d36d62c // indirect
+ golang.org/x/sys v0.0.0-20190507160741-ecd444e8653b // indirect
+ golang.org/x/text v0.3.2 // indirect
+ golang.org/x/tools v0.0.0-20190506145303-2d16b83fe98c // indirect
```

We think it has to do with installing `vim-go` with `:InstallBinaries` but we're not sure what's going on. When we set `:let $GO111MODULE = 'off'` in `before.vim` we don't get the updates to `go.mod` so it's trying to install something..

Have you seen behavior like this? Are we doing something wrong? Any help to get rid of the automatic go.mod updates would greatly appreciated!

**Comment by luan** [comment]
Do you have a minimal reproducible example repo I can play around with?

**Comment by Changdrew** [comment]
We think this happens because https://github.com/luan/nvim/blob/6c7522a2873eba4bb0b60381a6136eff92006f99/update.vim#L42-L45 runs on opening any go file. We (@vitreuz) tried to turn off auto-update through `let g:skip_autoupdate = 1` but that didn't disable the updating.

**Comment by vitreuz** [comment]
@luan here's an example repo

https://github.com/vitreuz/module-repro-bug

**Comment by luan** [comment]
@Changdrew that logic was added before [vim-go](https://github.com/fatih/vim-go) actually started installing `gopls`. I removed it now.

This issue is now only going to happen when running a fresh `:GoInstallBinaries` or `:GoUpdateBinaries` from a go mod project. So the problem is still present on [vim-go](https://github.com/fatih/vim-go).

I'm still looking at how we can mitigate it on this repo though it should be a bit better now.

**Comment by luan** [comment]
Aand it looks like [vim-go](https://github.com/fatih/vim-go) has actually already [dealt with this](https://github.com/fatih/vim-go/blob/b8684ab5f93ad752176cb1ddaef85273c6f24d7f/plugin/go.vim#L108).

I couldn't reproduce the problem with latest everything anymore so it seems like it may be fixed. Please re-open if this continues happening for you.
