### ISSUE TITLE
Status line separator characters do not display properly

### ISSUE THREAD

**Issue by georgethebeatle** [luan/nvim#17]
Hi Luan,

We at the Garden team are trying out this repository and we noticed that the light line status bar has is not rendered properly: on our machines we see a couple of question marks in boxes. It could be the font that we are using, but I guess it is not great to depend on a particular font. Maybe change those to some characters that are more generally available?

**Comment by luan** [comment]
You just need to install and use something like [nerd-fonts](https://nerdfonts.com/). I'll leave this issue open to add this to the README (it is documented on [Plugins.md](https://github.com/luan/nvim/blob/master/Plugins.md#itchynylightlinevim) though. I don't think I'll be changing those characters though as I really enjoy how they look right now.

It's worth noting also that if you want to do that locally, you can. Using the [user config hooks](https://nerdfonts.com/)  and changing the separator characters as described by `:help g:lightline.separator`.

**Comment by georgethebeatle** [comment]
Cool, thanks
