### ISSUE TITLE
Automatically update less often

### ISSUE THREAD

**Issue by XanderStrike** [luan/nvim#20]
> As a user of these nvim configs, I want to be interrupted by updates less often, so that my flow is broken less often.

Currently it seems like it updates whenever updates are available, which means my pair and I get stuck for 1-5 minutes watching it do its thing. This can be frustrating when we just wanna edit a little manifest or config file. I've been hit by updates 2+ times a day before which is a bummer. We've got 11 pairs in the networking program all using these configs, so 5 minutes adds up pretty fast 😂 

I definitely don't want to disable auto updating entirely though, because there's lots of good stuff here. I might propose creating a `stable` branch that we can follow, that just has all the changes from `master` merged into it weekly.

**Comment by luan** [comment]
@XanderStrike thanks for the feedback -- please read the detailed [commit message](https://github.com/luan/nvim/commit/2ef454edee4a2eb38b2358d929f5f9b938a5cb4a) for an explanation of how I tried to solve this!
