### ISSUE TITLE
Unknown function: SemshiBufWipeout

### ISSUE THREAD

**Issue by tscolari** [luan/nvim#30]
I'm just migrating from the old config, I've cleaned all the old files and started from scratch with this one (at least I hope).
But I'm getting this error when starting vim:

```
Error detected while processing BufWipeout Autocommands for "*":
E117: Unknown function: SemshiBufWipeout
```

Is there any dependency I'm missing?

**Comment by luan** [comment]
Does running `:UpdateRemotePlugins` fix it for you?

It's _supposed_ to do that automatically upon installation, but if for some reason that is missed, or you didn't have the correct python setup at the time (https://github.com/luan/nvim#installation) nothing will run try running it again.

I can try to think about ways to automate this fix though if that indeed was the problem.

**Comment by tscolari** [comment]
That seems to have worked! (running `:UpdateRemotePlugins`)
Not sure why it didn't run before, but it seems to have detected a config update and installed some "language servers" after that - the error message is gone!

**Comment by willmurphyscode** [comment]
I got this same error message when `pynvim` had not been installed on a new install. I also had to open nvim, run `:UpdateRemotePlugins`, close nvim, and re-open it, to stop seeing the error.

**Comment by benmoss** [comment]
Same, fresh install, errors, and then `:UpdateRemotePlugins` to fix
