### ISSUE TITLE
'set wrap' breaks ale or something?

### ISSUE THREAD

**Issue by XenoPhex** [luan/nvim#53]
Pretty sure this isn't a problem with your config, just using this issue as a means of communication.

Using a new checkout of the config and adding `set wrap` to the current session causes the error text pop-up to break [when your cursor is on the wrapped error line] with the following error:
```vim
Error detected while processing function ale#cursor#EchoCursorWarning[34]..<SNR>259_ShowCursorDetailForItem[8]..ale#floating_preview#Show:
line   45:
E5555: API call: Vim:E315: ml_get: invalid lnum: 2
Press ENTER or type command to continue
```

This is likely an error with the plugin [and the fact that I'm a monster and like my text wrapped]. I just need to figure out who to report this bug to.

**Comment by luan** [comment]
Odd... #55 doesn't use ALE anymore, so maybe that's ok ehehhee.

**Comment by XenoPhex** [comment]
I can switch to that branch and give it a try if you think it'll fix the issue.
