### ISSUE TITLE
fzf.vim commands not found

### ISSUE THREAD

**Issue by albertoleal** [luan/nvim#66]
Is there a way to enable the `fzf.vim` commands? >> https://github.com/junegunn/fzf.vim#commands

I see a "Not an editor command: XYZ" error whenever I try to run them. 

And, I have `ag`, `rg` installed..

**Comment by albertoleal** [comment]
Also, `<Ctrl-P>` does not work because of:  **Not an editor command: FZFFiles**

**Comment by luan** [comment]
I've always thought those were too generic and had too much potential for conflict, so I configure them with the `FZF` prefix: https://github.com/luan/nvim/blob/main/lua/plugins.lua#L54

They all work by pretending `FZF`. i.e. `:FZFAg` or `:FZFColors`

**Comment by albertoleal** [comment]
Oh, I didn't notice that! Cheers!
