### ISSUE TITLE
Support Macs with `arm` architecture

### ISSUE THREAD

**Issue by zaksoup** [luan/nvim#69]
The path `/usr/local` is protected by System Integrity Protection on Macs with Apple designed chips. To get around this I propose checking `uname -p` for the response `arm` and setting the `install_path` variable in `bin/install` to a more suitable path. I just used the homebrew path at `/opt/homebrew` because I already had `/opt/homebrew/bin` on my PATH.

**Comment by luan** [comment]
What's installing to `/usr/local`? I don't see that path referenced anywhere in the config. Is it possible this is some plugin trying to install dependencies? What error do you see? You should probably open an issue with the plugin if that's the case.

**Comment by albertoleal** [comment]
I have been using this config on my M1 without issues..
