### ISSUE TITLE
GoLang doesn't work on fresh installs on OS X

### ISSUE THREAD

**Issue by XenoPhex** [luan/nvim#8]
Looks like it's not installing/creating the `$HOME/.local/share/nvim/go` directory, nore are you able to run `:GoInstallBinaries` post install.

How to reproduce after XCode/command line tools is installed:
```bash
$ brew install python3 neovim
...
$ pip3 install neovim
...
$ nvim
...
$ ls $HOME/.local/share/nvim
plugged shada site swap undo view
```

**Comment by luan** [comment]
@XenoPhex got `:A` working through projectionist now.
Thanks for looking into it. Sorry it took me so long to get to this issue.

**Comment by luan** [comment]
And oh, pushed a commit that fixes fresh install by making that directory properly.
