### ISSUE TITLE
go plugin fails healthcheck with: "attempt to index global '_GO_NVIM_CFG' (a nil value)"

### ISSUE THREAD

**Issue by robdimsdale** [luan/nvim#85]
From a completely clean install of `neovim 0.7.0`, `pynvim 0.4.3`, and the latest config in this repo, I see lots of errors when interacting with golang files. Running `:checkhealth` shows the following:

```
  2 go: require("go.health").check()
  3 ========================================================================
  4   - ERROR: Failed to run healthcheck for "go" plugin. Exception:
  5     function health#check, line 20
  6     Vim(eval):E5108: Error executing lua ...re/nvim/site/pack/packer/start/go.nvim/lua/go/health.lua:17: attempt to index global '_GO_NVIM_CFG' (a nil value)
  7     stack traceback:
  8     ...re/nvim/site/pack/packer/start/go.nvim/lua/go/health.lua:17: in function 'binary_check'
  9     ...re/nvim/site/pack/packer/start/go.nvim/lua/go/health.lua:92: in function 'check'
 10     [string "luaeval()"]:1: in main chunk
```

https://github.com/ray-x/go.nvim/issues/112 may be related, and I tried adding `require("go").setup()` to my `before.lua` but that didn't change the behavior I observed.

**Comment by robdimsdale** [comment]
Also in case it's relevant, I'm using `go1.18.1 darwin/amd64`

**Comment by luan** [comment]
I can't seem to repro this, and the failure is coming from the plugin. Are you able to reproduce it consistently? It might be worth opening an issue on ray-x/go.nvim instead

**Comment by robdimsdale** [comment]
So, I can resolve this issue by adding `require'go'.setup()` to the `before.lua` in the `~/.config/nvim/lua/user/` directory. However, that seems like something that would be part of this config, rather than user-provided.

Without that change, it is 100% reproducible on my machine - uninstalling neovim (and the python plugins etc) and this config, and reinstalling it, and it consistently fails.

In my comment above I liked to a closed issue on `ray-x/go.nvim` which suggests that to fix the problem I'm having:

> Make sure require'go'.setup() is called before require'go.lsp'.config()

I don't understand enough of this flow to understand why I need to add this config explicitly whereas it just works for you.

That seems like the sort of thing that would belong in this config. I don't know where I would make that change - I tried

**Comment by luan** [comment]
You had said that adding that to `before.lua` didn't solve the problem, that's why I thought it'd be something else. I'll add it in the right place.

**Comment by luan** [comment]
Can you try after this change?

**Comment by robdimsdale** [comment]
That seems to fix it.

Before when I was reproducing it, I think I was accidentally adding the line `require'go'.setup()` to the `user.defaults/before.lua` not `user/before.lua`. But my understanding was that these two files would be processed the same way. Maybe I got that wrong.

**Comment by robdimsdale** [comment]
Thank you for adding this. I still don't understand why you weren't running into this. I assume you had updated all of your plugins?

**Comment by luan** [comment]
No idea why it wasn't happening for me, but yeah, updated and on multiple computers.

user.defaults is just a template that gets copied to the git ignored user folder. I admit that's a confusing thing since the folder is always there. I might spend some brain cycles trying to smooth that over later.

**Comment by robdimsdale** [comment]
Alright - I think we're good to close this now. Thank you for your help!
