### ISSUE TITLE
telescope find_files broken

### ISSUE THREAD

**Issue by benmoss** [luan/nvim#93]
I rely on `<leader>ff` a lot, and something seems to have been broken it recently. Nothing happens when I run the shortcut. `:Telescope find_files` and `:lua require("telescope.builtin").find_files()` both work.

As close to a repro as I can give:
- clone https://github.com/benmoss/gh-release-installer
- `nvim dependencies.go` followed by `<leader>ff` does nothing
- `nvim` followed by `<leader>ff` works. open `dependencies.go` and it breaks.

I tried bisecting and it pointed to either e4cf95b9c1941f00312c4517acfb70878b854ca3 or fac373728fa01f16393de93ab03966d65fa03956, it was kinda hard to be sure things were working on the old commits. Definitely seems like something LSP specific could be messing it up, since it only seems to crop up when I open a .go file.

I tried `nvim -v10` but didn't see anything obvious there either.

**Comment by luan** [comment]
I tried this on your repo and couldn't reproduce it. All `<space>ff` does is call `telescope.find_files` so I don't know why this would happen...

When the issue is happening, what output do you get from `:map <space>ff`?

I also made a change just now to remove conflicting bindings on `<space>g` but I don't think that should affect `<space>ff` (8ec7705)

**Comment by luan** [comment]
I found it, it was go.nvim. but those commits don't really explain it though. It might be https://github.com/luan/nvim/commit/2e106344f3e7f73aac699e4c2b4bb52026b17df3

**Comment by benmoss** [comment]
ah yup `:map <space>ff` reported

```
n  <Space>ff   *@<Cmd>lua vim.lsp.buf.formatting()<CR>
n  <Space>     * <Cmd>lua require("which-key").show(" ", {mode = "n", auto = true})<CR>
x  <Space>     * <Cmd>lua require("which-key").show(" ", {mode = "v", auto = true})<CR>
n  <Space>ff   * <Cmd>lua require("which-key").execute(10)<CR>
```
but now the `lua vim.lsp.buf.formatting()` is gone. you're the man luan 😄

**Comment by benmoss** [comment]
when are you going to start allowing us to fund your work on this project
