### ISSUE TITLE
Replace vim-ultest with neotest 

### ISSUE THREAD

**Issue by albertoleal** [luan/nvim#95]
`vim-ultest` has been deprecated in favour of `https://github.com/nvim-neotest/neotest`

This issue is about replacing the plugin and shortcuts, for instance <leader>+T ..

**Comment by luan** [comment]
I tried the new plugin but it chokes really badly on my mono repo, I don't really use ulttest at all, but i would love to get some of the debugger functionality from neotest/vim-dap. I'll keep some tabs open on this to figure out how to integrate this well.
